format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$character\
"""

add_newline = false

[username]
format = "[$user]($style)"
show_always = false

[hostname]
format = "[@$hostname:]($style)"
ssh_only = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " [RO]"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "

[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](red)"

